title: My GitHub Pages Site
description: This is a sample Jekyll site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kishensharma.com" # the base hostname for your site

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: G-MZTQMZDDVS
google_tag_manager:
# Bing services
bing_verification:

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
# Optional: set your layout defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"